version: '3.4'

services:
  postgresql:
    image: postgres:9.6-alpine
    environment:
      - POSTGRES_PASSWORD=root
    volumes:
      - ./configuration/postgresql/initdb:/docker-entrypoint-initdb.d
      - postgresqldata:/var/lib/postgresql/data
    networks:
      - corecmd_playground_network

  redis:
    image: redis:5-alpine
    volumes:
      - redisdata:/data
    networks:
      - corecmd_playground_network

  mongodb:
    image: mongo:latest
    container_name: 'rl_mongodb'
    ports:
      - 27017:27017
    volumes:
      - mongodb-data:/data/db
      - mongodb-config:/data/configdb
    networks:
      - corecmd_playground_network

  influxdb:
    image: quay.io/influxdb/influxdb:2.0.0-beta
    ports:
      - 9999:9999
    networks:
      - corecmd_playground_network

  grafana:
    image: grafana/grafana:latest
    ports:
      - 3000:3000
    networks:
      - corecmd_playground_network

networks:
  corecmd_playground_network:

volumes:
  postgresqldata:
  redisdata:
  mongodb-data:
  mongodb-config:

