version: "3.4"

services:
  influxdb:
    image: quay.io/influxdb/influxdb:2.0.0-beta
    ports:
      - 9999:9999
    networks:
      - corecmd_playground_network

  grafana:
    image: grafana/grafana:latest
    ports:
      # change the outer port to 13000 as hyper-v keep 3000 as reserved port
      - 13000:3000
    networks:
      - corecmd_playground_network

networks:
  corecmd_playground_network:

volumes:
  postgresqldata:
  redisdata:
  mongodb-data:
  mongodb-config:
